spring:
  application:
    name: kotlin-spring-boot-todo
  datasource:
    url: jdbc:h2:mem:tododb
    driver-class-name: org.h2.Driver
    username: app
    password: password
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
          orm:
            jdbc:
              bind: trace
  h2:
    console:
      enabled: true
  management:
    endpoints:
      web:
        exposure:
          include: '*'
