spring:
  application:
    name: kotlin-spring-boot-todo
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    driverClassName: org.postgresql.Driver
    username: app
    password: password
  flyway:
      enabled: true
      baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
      default_schema: public
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org:
        hibernate:
          type: trace
          orm:
            jdbc:
              bind: trace
  management:
    endpoints:
      web:
        exposure:
          include: '*'
